### ISSUE TITLE
MintCoin

### ISSUE THREAD

**Issue by jaekwon** [tendermint/basecoin-examples#5]
Cool.

I'd s/winner/???/g, make it less jocular, more plain.
I'd move all the new types into a "types" directory, and move the plugin into a "plugins" directory".

**Comment by ethanfrey** [comment]
Okay, I fixed up the naming (Issuers and Credits) and moved the files. Please look at commit 4190968

Also, given how small the package is (this is more like a "my first plugin" demo), I feel making two more subdirs only makes it more confusing and harder to find the code.  But I did standardize the names to `plugins.go` and `types.go`.

**Comment by ethanfrey** [comment]
I cleaned up the trader organization to match these suggestions (as there is much more code, it makes very good sense to have a plugins and types sub-packages).

Changes in f7ac153, 8fd0738, 07cf12c or just look at the recent version to see the layout.

**Comment by zramsay** [comment]
stale issue, has been handled
