### ISSUE TITLE
repo should be migrated into cosmos-academy repo

### ISSUE THREAD

**Issue by zramsay** [tendermint/basecoin-examples#9]
much easier to include as part of the `basecoin` test sequence, rather than, say #7

**Comment by rigelrozanski** [comment]
Agreed, need an examples directory probably under `cmd/` in basecoin repo
This all these examples should be cleaned up and merged into the basecoin once, `basecoin/unstable` has been finalized and merged. I can take this on

**Comment by rigelrozanski** [comment]
hmmm, Alternatively I think @ethanfrey seems to think that we should probably include all demo/non-production apps in a separate repos... As an alternative, I think we will be able to still test this repo as a part of the circle integration tests of basecoin... this way we can keep SDK clean while still maintain the example code

**Comment by zramsay** [comment]
https://github.com/cosmos/cosmos-academy/pull/10
